
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: knut
    ports:
      - 27055:27017
    volumes:
      - /mnt/disk2/mongo_data:/data/db
    networks:
      - ows


networks:
  ows:
    external: true
