
---
- hosts: ows-cli
  remote_user: mog
  vars_prompt:
    - name: "ansible_become_pass"
      prompt: "Sudo password"
      private: yes
  become: yes
  become_flags: "-E"
  gather_facts: yes

  tasks:

    - name: Delete directory
      file:
        state: absent
        path: "/var/www/ows-cli"

    - name: Create directory
      file:
        path: "/var/www/ows-cli"
        state: directory

    - name: Clone git repository
      git:
        repo: "git@github.com:schmidko/ows-cli.git"
        version: "main"
        dest: "/var/www/ows-cli/"
        force: yes
        accept_hostkey: yes
    
    - name: Copy env
      copy:
        src: "/home/mog/env/ows-cli/.env"
        dest: "/var/www/ows-cli/.env"
        remote_src: true

    - name: Install packages
      npm:
        path: "/var/www/ows-cli/"
